version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - SQLITE_DB_PATH=/app/data/speaksynth.db

volumes:
  sqlite_data:
    # Named volume to persist SQLite database between container restarts